name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

env:
  STORAGE_ACCOUNT_KEY: asfgfdg
  STORAGE_ACCOUNT_NAME: asfdgfsdfg

jobs:
  buildandtest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build