name: Build, Test and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    branches:
      - master

env:
  STORAGE_ACCOUNT_CONTAINER: $web
  STORAGE_ACCOUNT_CONNECTIONSTRING: DefaultEndpointsProtocol=https;AccountName=storagedemotest;AccountKey=IZOnaPGZI6bhCLcnVeAQLuz2rvCuVclHc01+vB5Skul1NP7hBgiKFFTNjiWEiqaef/+k7LtV5ErJCnShZk+tiQ==;EndpointSuffix=core.windows.net

jobs:
  buildandtest:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn build
        env:
          CI: false
      - uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          source_dir: build
          container_name: ${{ env.STORAGE_ACCOUNT_CONTAINER }}
          connection_string: ${{ env.STORAGE_ACCOUNT_CONNECTIONSTRING }}
          sync: false